# Generated by Django 3.2.4 on 2021-06-10 07:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtoJobCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg data entry', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MtoRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(help_text='eg assignees, admins, developers, evaluators', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MTOJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_mto_id', models.IntegerField(help_text='primary key of the assigned mto from mto table')),
                ('due_date', models.DateField()),
                ('assigned_date', models.DateField()),
                ('fees', models.FloatField()),
                ('rating', models.IntegerField(help_text='Rating/Evaluation')),
                ('payment_status', models.IntegerField(help_text='Mto payment status id')),
                ('completed_date', models.DateField(help_text='Completed Date')),
                ('output_path', models.FileField(default='output/default.pdf', help_text='path of submitted job', upload_to='output/%Y/%m/')),
                ('evaluation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.evaluationstatus')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.microtasks')),
            ],
        ),
        migrations.CreateModel(
            name='MtoAdminUsers',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
                ('name', models.CharField(max_length=100)),
                ('varal_role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.mtoroles')),
            ],
            options={
                'verbose_name': 'MTO Admin User',
                'verbose_name_plural': 'MTO Admin Users',
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='microtasks',
            name='category',
            field=models.ForeignKey(help_text='job category', on_delete=django.db.models.deletion.CASCADE, to='jobs.mtojobcategories'),
        ),
        migrations.AddField(
            model_name='evaluationstatus',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.microtasks'),
        ),
    ]
